[build]
  command = "npm run build:netlify && node netlify-image-fix.js"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./public/"

# Ensure all assets are copied to the dist folder
[build.processing]
  skip_processing = false

[build.processing.images]
  compress = true

[build.environment]
  NODE_VERSION = "20"

# Exclude Google verification file from SPA redirect
[[redirects]]
  from = "/googlea7b0d1994a9c267c.html"
  to = "/googlea7b0d1994a9c267c.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Content-Security-Policy = "default-src 'self' https: http:; img-src 'self' https: data: http:; style-src 'self' 'unsafe-inline' https: http:; font-src 'self' https: http:; script-src 'self' https: 'unsafe-inline';"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Add cache control for images
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.PNG"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon*.png"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/apple-touch-icon.png"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/manifest+json"